timeless:
  name: time-less-as-you-feel

server:
  # 服务器的HTTP端口，默认为8080
  port: 7777
  servlet:
    context-path: /timeless

# Spring配置
spring:
  application:
    name: ${timeless.name}
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.24.199.107/keria?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: Zz10221225
      type: com.alibaba.druid.pool.DruidDataSource

    redis:
      # 地址
      host: 175.24.199.107
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码(如没有密码请注释掉)
      # password:
      # 连接超时时间
      timeout: 10s
      # 是否开启ssl
      ssl: false

